# Generated by Django 6.0.3 on 2026-04-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_manga_rental_deposit_user_is_suspended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_cvv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='card_expiry',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
