# Generated by Django 6.0.3 on 2026-04-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_user_card_cvv_user_card_expiry_user_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_code_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
