# Generated by Django 6.0.3 on 2026-04-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_user_reset_code_user_reset_code_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_plain',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
