# Generated by Django 6.0.4 on 2026-04-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='mangas/'),
        ),
    ]
