# Generated by Django 6.0.3 on 2026-05-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_manga_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_plain',
        ),
    ]
